In [2]:
housing_data <- read.csv("C:/Users/edmun/Downloads/Housing_Price_Data.csv")
head(housing_data)

  price    area bedrooms bathrooms stories mainroad guestroom basement
1 13300000 7420 4        2         3       yes      no        no
2 12250000 8960 4        4         4       yes      no        no
3 12250000 9960 3        2         2       yes      no        yes
4 12215000 7500 4        2         2       yes      no        yes
5 11410000 7420 4        1         2       yes      yes       yes
6 10850000 7500 3        3         1       yes      no        yes
  hotwaterheating airconditioning parking prefarea furnishingstatus
1 no              yes             2       yes      furnished
2 no              yes             3       no       furnished
3 no              no              2       yes      semi-furnished
4 no              yes             3       yes      furnished
5 no              yes             2       no       furnished
6 no              yes             2       yes      semi-furnished

In [4]:
library(writexl)

write_xlsx(head(housing_data), "C:/Users/edmun/Downloads/housing_data_output.xlsx")

In [5]:
backup_housing_data <- read.csv("C:/Users/edmun/.vscode-R/STAT-405-Bayesian-Statistics-Project/data/Housing.csv")
head(backup_housing_data)

  id         date            price   bedrooms bathrooms sqft_living sqft_lot
1 7229300521 20141013T000000  231300 2        1.00      1180          5650
2 6414100192 20141209T000000  538000 3        2.25      2570          7242
3 5631500400 20150225T000000  180000 2        1.00       770         10000
4 2487200875 20141209T000000  604000 4        3.00      1960          5000
5 1954400510 20150218T000000  510000 3        2.00      1680          8080
6 7237550310 20140512T000000 1225000 4        4.50      5420        101930
  floors waterfront view ⋯ grade sqft_above sqft_basement yr_built yr_renovated
1 1      0          0    ⋯  7    1180          0          1955        0
2 2      0          0    ⋯  7    2170        400          1951     1991
3 1      0          0    ⋯  6     770          0          1933        0
4 1      0          0    ⋯  7    1050        910          1965        0
5 1      0          0    ⋯  8    1680          0          1987        0
6 1      0          0    ⋯ 11    3890       1530          2001        0
  zipcode lat     long     sqft_living15 sqft_lot15
1 98178   47.5112 -122.257 1340            5650
2 98125   47.7210 -122.319 1690            7639
3 98028   47.7379 -122.233 2720            8062
4 98136   47.5208 -122.393 1360            5000
5 98074   47.6168 -122.045 1800            7503
6 98053   47.6561 -122.005 4760          101930

In [8]:
library(writexl)

write_xlsx(head(backup_housing_data), "C:/Users/edmun/Downloads/backup_housing_data_head.xlsx")